package org.freekode.tp2intervals.integration.platform.trainingpeaks.workout.dto

import org.freekode.tp2intervals.integration.platform.trainingpeaks.workout.structure.TPWorkoutStructureDTO
import java.time.LocalDateTime

class TPWorkoutCalendarDTO(
    workoutId: Long,
    workoutDay: LocalDateTime,
    athleteId: Long?,
    workoutTypeValueId: Int,
    workoutType: String?,
    title: String?,
    description: String?,
    coachComments: String?,
    startTime: String?,
    startTimePlanned: String?,
    lastModifiedDate: String?,
    totalTimePlanned: Double?,
    tssPlanned: Int?,
    ifPlanned: Double?,
    distancePlanned: Double?,
    caloriesPlanned: Double?,
    energyPlanned: Double?,
    elevationGainPlanned: Double?,
    velocityPlanned: Double?,
    totalTime: Double?,
    distance: Double?,
    calories: Int?,
    energy: Double?,
    rpe: Int?,
    feeling: Int?,
    `if`: Double?,
    tssSource: Int?,
    tssActual: Int?,
    normalizedPowerActual: Double?,
    powerAverage: Double?,
    powerMaximum: Double?,
    torqueAverage: Double?,
    torqueMaximum: Double?,
    heartRateAverage: Int?,
    heartRateMaximum: Int?,
    heartRateMinimum: Int?,
    cadenceAverage: Int?,
    cadenceMaximum: Int?,
    elevationGain: Double?,
    elevationLoss: Double?,
    elevationAverage: Double?,
    elevationMaximum: Double?,
    elevationMinimum: Double?,
    velocityAverage: Double?,
    velocityMaximum: Double?,
    normalizedSpeedActual: Double?,
    complianceTssPercent: Double?,
    complianceDurationPercent: Double?,
    complianceDistancePercent: Double?,
    personalRecordCount: Int?,
    orderOnDay: Int?,
    userTags: String?,
    isItAnOr: Boolean?,
    publicSettingValue: Int?,
    sharedWorkoutInformationKey: String?,
    sharedWorkoutInformationExpireKey: String?,
    completed: Boolean?,
    isLocked: Boolean?,
    isHidden: Boolean?,
    workoutDeviceSource: String?,
    hasPrivateWorkoutNoteForCaller: Boolean?,
    code: String?,
    workoutSubTypeId: Int?,
    equipmentBikeId: Long?,
    equipmentShoeId: Long?,
    poolLengthOptionId: Int?,
    structure: TPWorkoutStructureDTO?,
    workoutComments: List<TPWorkoutCommentDTO> = emptyList(),
    tempMax: Double?,
    tempMin: Double?,
    tempAvg: Double?,
    syncedTo: List<String>? = emptyList(),
    newComment: String?,
    distanceCustomized: Double?,
    distanceUnitsCustomized: Int?
) : TPBaseWorkoutDTO<TPWorkoutStructureDTO>(
    workoutId = workoutId,
    athleteId = athleteId,
    workoutTypeValueId = workoutTypeValueId,
    workoutType = workoutType,
    title = title,
    description = description,
    coachComments = coachComments,
    workoutDay = workoutDay,
    startTime = startTime,
    startTimePlanned = startTimePlanned,
    lastModifiedDate = lastModifiedDate,
    totalTimePlanned = totalTimePlanned,
    tssPlanned = tssPlanned,
    ifPlanned = ifPlanned,
    distancePlanned = distancePlanned,
    caloriesPlanned = caloriesPlanned,
    energyPlanned = energyPlanned,
    elevationGainPlanned = elevationGainPlanned,
    velocityPlanned = velocityPlanned,
    totalTime = totalTime,
    distance = distance,
    calories = calories,
    energy = energy,
    rpe = rpe,
    feeling = feeling,
    `if` = `if`,
    tssSource = tssSource,
    tssActual = tssActual,
    normalizedPowerActual = normalizedPowerActual,
    powerAverage = powerAverage,
    powerMaximum = powerMaximum,
    torqueAverage = torqueAverage,
    torqueMaximum = torqueMaximum,
    heartRateAverage = heartRateAverage,
    heartRateMaximum = heartRateMaximum,
    heartRateMinimum = heartRateMinimum,
    cadenceAverage = cadenceAverage,
    cadenceMaximum = cadenceMaximum,
    elevationGain = elevationGain,
    elevationLoss = elevationLoss,
    elevationAverage = elevationAverage,
    elevationMaximum = elevationMaximum,
    elevationMinimum = elevationMinimum,
    velocityAverage = velocityAverage,
    velocityMaximum = velocityMaximum,
    normalizedSpeedActual = normalizedSpeedActual,
    complianceTssPercent = complianceTssPercent,
    complianceDurationPercent = complianceDurationPercent,
    complianceDistancePercent = complianceDistancePercent,
    personalRecordCount = personalRecordCount,
    orderOnDay = orderOnDay,
    userTags = userTags,
    isItAnOr = isItAnOr,
    completed = completed,
    isLocked = isLocked,
    isHidden = isHidden,
    publicSettingValue = publicSettingValue,
    sharedWorkoutInformationKey = sharedWorkoutInformationKey,
    sharedWorkoutInformationExpireKey = sharedWorkoutInformationExpireKey,
    workoutDeviceSource = workoutDeviceSource,
    hasPrivateWorkoutNoteForCaller = hasPrivateWorkoutNoteForCaller,
    code = code,
    workoutSubTypeId = workoutSubTypeId,
    equipmentBikeId = equipmentBikeId,
    equipmentShoeId = equipmentShoeId,
    poolLengthOptionId = poolLengthOptionId,
    structure = structure,
    workoutComments = workoutComments,
    syncedTo = syncedTo,
    newComment = newComment,
    tempMax = tempMax,
    tempMin = tempMin,
    tempAvg = tempAvg,
    distanceCustomized = distanceCustomized,
    distanceUnitsCustomized = distanceUnitsCustomized
)