app:
  training-peaks:
    api-url: https://tpapi.trainingpeaks.com
  intervals:
    api-url: https://intervals.icu
  trainer-road:
    api-url: https://www.trainerroad.com
  mfp:
    api-url: https://www.myfitnesspal.com
  strava:
    api-url: https://www.strava.com
  rouvy:
    account-url: https://account.rouvy.com
    api-url: https://riders.rouvy.com
  wahoo:
    api-url: https://api.wahooligan.com

  attachments:
    enabled: true

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:sqlite:tp2intervals.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  port: 8080
  error:
    include-message: always
  compression:
    enabled: true

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: 'health,info,loggers'
      cors:
        allowed-origins: '*'
  endpoint:
    loggers:
      enabled: true

logging:
  level:
    org.freekode.tp2intervals.integration.platform: DEBUG
  file:
    name: tp2intervals.log
