name: CI/CD Pipeline - Deploy to VPS

on:
  push:
    branches:
      - feature/vps # Dispara o deploy toda vez que você der 'git push' na branch dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura o Java para compilar o Backend
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # 3. Compila o Backend (Gera o boot.jar) com Gradle
      - name: Build Backend with Gradle
        run: |
          cd boot
          chmod +x gradlew
          ./gradlew bootJar --no-daemon

      # 4. Conecta no seu Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Builda e Envia o container do Backend para o Docker Hub
      - name: Build and push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Garanta que esse Dockerfile usa o boot.jar gerado no step 3
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp2intervals-backend:latest

      # 6. Builda e Envia o container do Frontend (O Dockerfile multi-stage compila o Angular)
      - name: Build and push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp2intervals-frontend:latest

      # 7. ENTRADA NA VPS VIA SSH: O GitHub entra na sua Oracle e atualiza os containers
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}       # IP da sua VPS
          username: ${{ secrets.VPS_USER }}   # Normalmente 'ubuntu'
          key: ${{ secrets.VPS_SSH_KEY }}     # Sua chave privada (.key ou .pem) para entrar na VPS
          script: |
            cd /var/www
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
            echo "Deploy na VPS finalizado com sucesso!"
